name: Deploy
on:
  push:
    branches:
      - main  # 确保这里是你存放代码的分支名
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 重要：允许写入权限
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install --legacy-peer-deps
          npm run build
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build # React 项目执行 npm run build 后生成的文件夹名称